sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
git:
  depth: 3
notifications:
  email: false
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run test
  # - npm run check-coverage
after_success:
  # - npm run report-coverage
  # - npm run semantic-release
